#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cachou.Resource", IsApplication=true)]

namespace Cachou
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int age = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bandaid = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bear = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int blood = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int blue_bandaid = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int blue_heart = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int blue_pills = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int blue_siringe = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Cachou = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Cachou_Confu = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Cachou_happy = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Cachou_triste = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int clipboard = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int coloring = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int croix_rouge = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int fox = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int girafe = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int heart = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int home = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int interest = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int justine = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int justine_docteur = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Les_animaux_autour_du_monde = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int login_button = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int medecine = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int mute = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int name = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int panda = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int placeholder = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int siringe = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ste_justine = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int thermometer = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001c
			public const int MyButton = 2131099676;
			
			// aapt resource value: 0x7f06000c
			public const int bear1 = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int bear2 = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int bear3 = 2131099668;
			
			// aapt resource value: 0x7f06000a
			public const int button1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int choose_nurse = 2131099659;
			
			// aapt resource value: 0x7f060016
			public const int coloring = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int coloring_nurse = 2131099669;
			
			// aapt resource value: 0x7f06001b
			public const int editText1 = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int editText2 = 2131099673;
			
			// aapt resource value: 0x7f06000d
			public const int fox1 = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int fox2 = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int girafe1 = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int girafe2 = 2131099666;
			
			// aapt resource value: 0x7f060018
			public const int imageView1 = 2131099672;
			
			// aapt resource value: 0x7f06001d
			public const int imageView2 = 2131099677;
			
			// aapt resource value: 0x7f060003
			public const int imageViewCachou = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int outil1 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int outil2 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int outil3 = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int outil4 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int outil5 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int outil6 = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int panda1 = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int panda2 = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int seekBar = 2131099657;
			
			// aapt resource value: 0x7f06001a
			public const int textView1 = 2131099674;
			
			// aapt resource value: 0x7f060008
			public const int textView2 = 2131099656;
			
			// aapt resource value: 0x7f060017
			public const int to_color = 2131099671;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CachouMain = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int audio1 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int audio2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int audio3 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int audio4 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int audio5 = 2130968580;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
