#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cachou.Resource", IsApplication=true)]

namespace Cachou
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int age = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bandaid = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int blood = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int blue_bandaid = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int blue_heart = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int blue_pills = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int blue_siringe = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Cachou = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Cachou_Confu = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Cachou_happy = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Cachou_triste = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int dossier = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int heart = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int home = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int interest = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int justine = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Les_animaux_autour_du_monde = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int login_button = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int medecine = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int mute = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int name = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int siringe = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int thermometer = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int MyButton = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int Pause = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int editText1 = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int editText2 = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int imageView2 = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int imageView3 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int imageViewCachou = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int seekBar = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int textView1 = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int textView2 = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CachouMain = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
